// 这个模块存放全局常量。

const TOKEN_COOKIE_NAME = "token"
const TOKEN_COOKIE_MAX_AGE = 60 * 60 * 24 * 30
const AUTH_CACHE_TTL = 60 * 60 * 24 * 30
const PHOTO_LIST_PAGE_SIZE = 100
const SETTING_KEY = 'system-config'
const CAPTCHA_CACHE_TTL = 5 * 60
const CAPTCHA_LENGTH = 4
// 登录连续失败多少次后锁定账号。
const LOGIN_FAIL_MAX = 5
// 账号锁定时长（秒），15 分钟。
const LOGIN_LOCK_TTL = 15 * 60

export { TOKEN_COOKIE_NAME, TOKEN_COOKIE_MAX_AGE, AUTH_CACHE_TTL, PHOTO_LIST_PAGE_SIZE, SETTING_KEY, CAPTCHA_CACHE_TTL, CAPTCHA_LENGTH, LOGIN_FAIL_MAX, LOGIN_LOCK_TTL }
